### ISSUE TITLE
Csv doesn't have header

### ISSUE THREAD

**Issue by SauravDas90** [krishnadey30/LeetCode-Questions-CompanyWise#1]
The CSV doesnt have headers, so lets take the below example

Guess the Word | 46.1% | Hard | **1.2138391004755573** | https://leetcode.com/problems/guess-the-word

what does **1.2138391004755573** stands for? If feasible could you please update the data ?

**Comment by krishnadey30** [comment]
It's the frequency. I am not having a premium account as of now.

The order is as follows


Title |  Acceptance | Difficulty | Frequency | Link
-- | -- | -- | -- | --

**Comment by SauravDas90** [comment]
Frequency:-  1.2138391004755573 ,

is there any mathematical expression behind it. I totally understand that its sorted by Frequency of descending order.

**Comment by krishnadey30** [comment]
It's the value generated by Leetcode. No Idea on how they do it

**Comment by SauravDas90** [comment]
Will close the issue
